services:

  db:
    container_name: postgres_db
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - '.env'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d todo -U postgres1" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - custom

  app:
    container_name: django_app
    build: .
    expose:
      - 8000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/ToDo_HTMX
    networks:
      - custom
    command: bash -c "python3 manage.py migrate && gunicorn ToDo_HTMX.wsgi -b 0.0.0.0:8000"
#      ./wait.sh db
#      && python3 manage.py migrate
#      && gunicorn ToDo_HTMX.wsgi -b 0.0.0.0:8000
#      "
  nginx:
    build: ./nginx
    ports:
      - '8888:80'
    networks:
      - custom
    depends_on:
      - app


networks:
  custom:
    driver: bridge

volumes:
  app_data:
    name: "django_app_data"
