# Generated by Django 4.2.2 on 2023-06-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_finished',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
