# Generated by Django 4.2.2 on 2023-06-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_deadline_alter_todo_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='create_by',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_finished',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
